@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "org.example.CarUp.Enumerators.TypeGearBox",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_84261867 { 
   	label=CarUp
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Car404469113[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Car</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   bodyColor: Color [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   bodyType: TypeCar [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   engineCap: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fuelType: TypeFuel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   gearBoxType: TypeGearBox [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   make: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   model: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   numberWheels: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ maintenance()</TD></TR>
<TR><TD ALIGN="LEFT" >+ movement()</TD></TR>
<TR><TD ALIGN="LEFT" >+ turnLights(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ turnWrappers(): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Pickup404469113[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Pickup</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   loadCap: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ fuel()</TD></TR>
<TR><TD ALIGN="LEFT" >+ wipHeadlights()</TD></TR>
<TR><TD ALIGN="LEFT" >+ wipMirrors()</TD></TR>
<TR><TD ALIGN="LEFT" >+ wipWindshield()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TypeGearBox115294974[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(E)TypeGearBox</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   AUTO: TypeGearBox [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   CVT: TypeGearBox [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   MAN: TypeGearBox [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ valueOf(name: String): TypeGearBox</TD></TR>
<TR><TD ALIGN="LEFT" >+ values(): TypeGearBox[]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#DCFBD5"
];
} 
} 

'edges    
Car404469113 -> Pickup404469113[arrowhead=none, arrowtail=empty, dir=both];
Car404469113 -> TypeGearBox115294974[label="gearBoxType
[0..1]"];
    
}
@enduml